
x-configs: &common_config
  restart: always
  env_file:
    - .env
  networks:
    - app-network

services:
  # WebSocket/API для клиентов
  client-ws:
    <<: *common_config
    container_name: client-ws
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: ${FASTAPI_ENV}
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    <<: *common_config
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis

  nginx:
    <<: *common_config
    image: nginx:1.23-alpine
    container_name: my_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  timescaledb:
    <<: *common_config
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    volumes:
      - tsdb_data:/var/lib/postgresql/data
    profiles: [ "with-timescale" ]

volumes:
  tsdb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
