gzip on;
gzip_min_length 200;
gzip_comp_level 3;
gzip_disable "msie6";
gzip_types
  text/plain
  text/css
  text/javascript
  text/xml
  application/javascript
  application/x-javascript
  application/json
  application/xml;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}


server {
    listen              443 ssl http2;
    server_name         ${APP};
    ssl_certificate     /etc/letsencrypt/live/${APP}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${APP}/privkey.pem;


    root /data;

    large_client_header_buffers 2 12k;

    client_max_body_size 20M;

    location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

    location / {
        try_files $uri @proxy_to_app;
    }


    location @proxy_to_app {
        proxy_pass http://app:8080;
        include /etc/nginx/user.conf.d/proxy.conf;
    }
}
